### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by Chalsean** [tukui-org/ElvUI#1105] opened 2023-11-17 15:01 UTC
### Troubleshooting Steps

Since the release of 13.51 (I think), keybinds will not work unless the associated action bar is enabled.  If the action bar is not enabled, the keybind no longer works.  Rolling back to 13.48 fixed this issue (it's the version I had in backups).  I tried 13.52 recently as well and issue still persists, again rolling back to 13.48 fixed the issue.

![Screenshot 2023-11-17 075736](https://github.com/tukui-org/ElvUI/assets/45693161/027fdbac-43c3-49eb-8375-a85fead09445)

### Describe the expected behavior and what actually happened?

Regardless of whether the action bar is enabled or not, the keybind should fire the associated spell on the action bar.

### Reproducing the issue.

Keep in mind I use Razer Tartarus for keybinds, altho that shouldnt make a diff.

1. Keybind an action bar entry.  I use action bars 3-6 for my combat spells.
2. Place spell in the keybound entry.
3. Disable the action bar.
4. Pressing the keybind no longer calls the associated spell.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2023-11-17 16:33
Yes, there has been a change to improve the performance of ElvUI
The bars that are disabled now cannot be used - they are properly disabled.

There is already an option to put hide in the action bar visibility state

• Actionbars which were disabled but used for keybinds, now need to be enabled and visibility state changed to hide to work like before

From the changelog

Duplicate of https://github.com/tukui-org/ElvUI/issues/1095

**Comment by kodewdle** [comment] 2023-11-17 21:53
closing because duplicate

**Closed by kodewdle** 2023-11-17 21:53 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Retail 🐲
