### ISSUE TITLE
Demote/promote/kick functions are not working

### ISSUE THREAD

**Issue by Shaterhand** [tukui-org/ElvUI#1055] opened 2023-09-29 08:43 UTC
### What is the issue you are having?

Whenever I try to demote/promote/kick someone from the guild I get an Lua error and the action doesn't happen.

### What is the expected behavior?

I should be able to demote/promote/kick someone from the guild.

### What actually happened?

I get an lua error and nothing happens.

### Errors

```shell
2x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_Libraries' tried to call the protected function 'GuildDemote()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `GuildDemote'
[string "*FriendsFrame.xml:3848_OnClick"]:1: in function <[string "*FriendsFrame.xml:3848_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment] 2023-09-30 08:08
duplicate of https://github.com/tukui-org/ElvUI/issues/68 however i will keep this open because we should track a new issue for it

**Comment by kodewdle** [comment] 2024-08-27 04:22
since The War Within is out and this is a taint, reopen if you still have the issue please :)

**Closed by kodewdle** 2024-08-27 04:22 UTC
Labels: 🧬 Wrath ❄️, 🐛 Possibly Unfixable ⚠️
