### ISSUE TITLE
Chat window problem

### ISSUE THREAD

**Issue by aderill** [tukui-org/ElvUI#228] opened 2022-04-27 08:59 UTC
### What is the issue you are having?

I wanted to separeted chat window frame side by side  (for example: one of main chat frame, one of whisper chat frame...) 

When i create a new chat window, and move out from the main chat frame, everything is ok! 
Changed background color and size, and position, and play, everything is fine.
But if i do any relog or reload UI process, the chat frame is change. BG color is change (it seems reset to white), position and size is change too.

So please, can you fix it ? 

ElvUi: 12.76
Shadow & Light: 4.36

### What is the expected behavior?

Expected behavior is: do not change settings when I log in

This happend when i log in, or relog, or type reload UI. The new frame window is moved, and bg color is change to white.
![elvui chat window problem](https://user-images.githubusercontent.com/104493208/165480689-7d4bd6e4-311a-45f5-9c93-d9695058c9ca.jpg)

### What actually happened?

If i do any relog or reload UI process, the chat frame is change. BG color is change (it seems reset to white), position and size is change too.

### Suggested Solution/Workaround

Fix the code :)

### Errors

```shell
i don't get an error, only the settings are lost
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment] 2022-05-15 00:30
can't reproduce with only elvui, closing

**Closed by kodewdle** 2022-05-15 00:30 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
