### ISSUE TITLE
[Retail Bug Report] Nameplate lua error while going M+

### ISSUE THREAD

**Issue by Bahamut117** [tukui-org/ElvUI#992] opened 2023-06-05 22:03 UTC
### What is the issue you are having?

While iam going M+ with some friends this error pops up.

### What is the expected behavior?

Everthing going as normal, i guess?

### What actually happened?

After deactivating nameplate addons and debug mode , the error stills comes up

### Errors

```shell
Message: .../AddOns/ElvUI/Core/Modules/Nameplates/Nameplates.lua:907: calling 'Hide' on bad self (Usage: self:Hide())
Time: Mon Jun  5 23:46:04 2023
Count: 4
Stack: .../AddOns/ElvUI/Core/Modules/Nameplates/Nameplates.lua:907: calling 'Hide' on bad self (Usage: self:Hide())
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/ElvUI/Core/Modules/Nameplates/Nameplates.lua"]:907: in function <.../AddOns/ElvUI/Core/Modules/Nameplates/Nameplates.lua:902>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:206: in function `OnTargetChanged'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:83: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:69>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: (*temporary) = <function> defined =[C]:-1
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment] 2023-06-06 06:23
ElvUI - Nameplate - Reset Cvars

Click on that and test. 

If you still have issues, please type in chat in game
`/edebug on` 
and test
If there is still errors, type in chat in game
`/estatus` 
and upload a full UI screenshot showing both the status panel and the error.

**Comment by 1Botanica1** [comment] 2023-06-12 11:55
Duplicate of #988

**Comment by kodewdle** [comment] 2023-07-14 10:07
continue on https://github.com/tukui-org/ElvUI/issues/988

**Closed by kodewdle** 2023-07-14 10:07 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
