### ISSUE TITLE
[Feature Request] Add nameplate cast bars adjustments to nameplate style filters.

### ISSUE THREAD

**Issue by Trenchfoote** [tukui-org/ElvUI#1093] opened 2023-11-13 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Nope, just a feature request to further enhance style filter functionality. 

**Describe the solution you'd like**
Additional option selections in "actions" for style filters to include adjusting/overriding the color and texture of the cast bar on nameplates. 

**Describe alternatives you've considered**
Plater with appropriate mods, mMediaTag and Tools has this option via a plugin, though it's per spell instead of a list of spells (meaning, each spell gets a set of options, as opposed to a grouping of spell id's for the trigger). 

**Additional context**
None, keep up the awesome work!

**Comment by mBlinkii** [comment] 2023-11-13 20:03
Yes, pls we need this for M+ ;D

**Comment by kodewdle** [comment] 2023-11-16 05:33
duplicate of already accepted issue https://github.com/tukui-org/ElvUI/issues/815 but thanks for the reminder it's still something i do want to add.

**Closed by kodewdle** 2023-11-16 05:33 UTC
