### ISSUE TITLE
[Retail Bug Report] ESC doesn't close world map in combat

### ISSUE THREAD

**Issue by mnejing** [tukui-org/ElvUI#686] opened 2022-12-08 01:35 UTC
### What is the issue you are having?

Sometime in the very recent past, ESC has stopped closing the world map when in combat. Using the keybind (M for me) does close it, but that's a really weird reach when you're, you know, in combat. Escape does close the window when not in combat. 

There are no taints I can see. No errors are being thrown at all. 

### What is the expected behavior?

Escape should close the world map when in combat... as it always has. 

### What actually happened?

It doesn't close the window. 

### Suggested Solution/Workaround

No idea. Gonna go ahead and guess it's something with the secure handler trying to prevent a taint. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment] 2022-12-13 18:00
@mnejing 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

Share more Data (Video etc.)

**Comment by kodewdle** [comment] 2022-12-16 20:53
can't confirm this, i would assume it happens when you have the options open and "close" it in combat OR if you have Edit Mode open and "close" it in combat; those closes are fake and technically would block something else like the map closing i guess.  closing this just because i can't reproduce it with just elvui reopen if you have more info

**Closed by kodewdle** 2022-12-16 20:53 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail

**Comment by mnejing** [comment] 2022-12-18 10:44
Hi.

So I didn't get a chance to reply back to this because of other commitments. I originally tracked this issue down to another addon that was intermittently causing issues and honestly forgot to come back here to reply. There was some persistent taint that wasn't clearing with /edebug on, which was when I wrote my original post. A complete closing of the client and then doing /edebug on did resolve the issue, and ultimately allowed me to track down the offender. 

However, since 13.11 came out, the issue has returned. And instead of it being specific to an addon, it's 100% an issue in ElvUI. 

Immediately prior to taking this screenshot, I confirmed that, when in combat, I could not close my map (or any other window, when it was limited to just my map prior to 13.11). 

Again, there are no lua errors, just a standard taint (Interface action failed).

![image](https://user-images.githubusercontent.com/31494988/208293804-7f8686d6-4b99-42e8-9cc2-261a11d87af1.png)

**Comment by RAtwood90** [comment] 2022-12-19 09:46
> Hi.
> 
> So I didn't get a chance to reply back to this because of other commitments. I originally tracked this issue down to another addon that was intermittently causing issues and honestly forgot to come back here to reply. There was some persistent taint that wasn't clearing with /edebug on, which was when I wrote my original post. A complete closing of the client and then doing /edebug on did resolve the issue, and ultimately allowed me to track down the offender.
> 
> However, since 13.11 came out, the issue has returned. And instead of it being specific to an addon, it's 100% an issue in ElvUI.
> 
> Immediately prior to taking this screenshot, I confirmed that, when in combat, I could not close my map (or any other window, when it was limited to just my map prior to 13.11).
> 
> Again, there are no lua errors, just a standard taint (Interface action failed).
> 
> ![image](https://user-images.githubusercontent.com/31494988/208293804-7f8686d6-4b99-42e8-9cc2-261a11d87af1.png)

Closed was the right choice cause...

**I have verfied ElvUI is up to date by checking /estatus.**

![UhavetoUpdate](https://user-images.githubusercontent.com/73589071/208396531-acc9975d-0b5f-46d1-b1e2-1803b905b8e4.png)
