### ISSUE TITLE
[Retail Bug Report] Expandable spells throwing error

### ISSUE THREAD

**Issue by Palanthis2** [tukui-org/ElvUI#491] opened 2022-11-01 14:52 UTC
### What is the issue you are having?

When clicking on an expandable spell, such as a Mage's Teleport, a Hunter's Call Pet, or a Rogue's Poisons spell, where the button should open up a list of choices, the following error is generated. I have disabled ElvUI and confirmed that the spell(s) work correctly with all other addons enabled.

Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Tue Nov  1 10:45:58 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>

### What is the expected behavior?

The button should expand a list of choices, that the user can then click on.

### What actually happened?

lua error:
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Tue Nov  1 10:45:58 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Tue Nov  1 10:45:58 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment] 2022-11-01 15:43
Duplicate of like 20 other tickets. Check known issues.

**Closed** 2022-11-01 15:42 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
