### ISSUE TITLE
Lura error

### ISSUE THREAD

**Issue by Milky063** [tukui-org/ElvUI#1142] opened 2023-12-27 18:40 UTC
### Troubleshooting Steps

done

### Describe the expected behavior and what actually happened?

zone into dungeon

### Reproducing the issue.

i zone in and out. 

### Lua Errors

```shell
9x ElvUI/Core/General/Math.lua:311: script ran too long
[string "@ElvUI/Core/General/Math.lua"]:311: in function <ElvUI/Core/General/Math.lua:311>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "collect"
(*temporary) = 0
(*temporary) = "script ran too long"
func = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
data = <table> {
 1 = "collect"
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2023-12-27 19:06
No, the troubleshooting steps aren't 'done' you haven't provided the screenshots requested! 


Type in game `/edebug on` 

Test - do you have the issue? 

If so, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the error and the status panel.

**Comment by 1Botanica1** [comment] 2023-12-28 04:19
Please stop creating new tickets re the same thing. 

This is the third ticket you have created for this. And on none of the tickets have you provided the troubleshooting information requested. 

Duplicate of #1138 
Duplicate of #1133

**Comment by Milky063** [comment] 2023-12-28 04:39
like i said before i
 just posting the error. if you want to fix it well thats up to you. its your addon, have a good day.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 1Botanica1** [comment] 2023-12-28 04:58
Like I said before, you need to do the troubleshooting steps, posting a random error with no information isn't of any use.  

Please stop creating new tickets re the same thing, especially when not providing the requested information

**Closed** 2023-12-29 14:14 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Retail 🐲
