### ISSUE TITLE
[Retail Bug Report] Bags / Bank window closes upon interaction

### ISSUE THREAD

**Issue by tryallthethings** [tukui-org/ElvUI#618] opened 2022-11-21 19:10 UTC
### What is the issue you are having?

Every time you want to store something in the bank or retrieve something from the bank, both (bag and bank) windows close. Additionally, upon reopening the bank window, the items stored are not updated properly. The mouseover tooltip shows the item, but it is not visually represented. The issue started after updating from ElvUI 13.03 to 13.04.

Here's some more Detail I wrote on Discord. But this feels like the appropriate place to report:

https://discord.com/channels/209244641537556480/222356141785612288/1044228866870358037
> Hello! Just wand to chime in on the bank issue. I updated from 13.03 to 13.04 yesterday which caused the issue to start appearing for me. No settings were changed. I can't even drag around items in my bank nor take items out. The bank and my bag windows are just closed every time. With ElvUI completely or just all-in-one bag disabled it works just fine. No errors / LUA errors are shown in chat or logged within Bugsack. Additionally the icon colors (rare, epic, etc) in my bank aren't shown anymore.

![Wow_2022-11-21_13-24-54](https://user-images.githubusercontent.com/11146296/203138885-96b42d88-46ec-4971-b3b2-fa626cc7e1b4.jpg)

https://discord.com/channels/209244641537556480/222356141785612288/1044230677123567616
> With Vokun Χ Ξ Σ suggestion to disable auto toggle for Bank everything seems to work normal. If you disable auto toggle you can use the bank normally sometimes. After 1 transaction (e.g. moving an item to the bank) you can sometimes re-enable the auto toggle for the bank and it works normal until you do a /rl. While testing I also noticed that items "disappear" when I try to move them to my bank with right click when the issue occurs. They only "reappear" once you disable auto toggle and do another transaction. 

Here's a short video showing the issue: https://www.youtube.com/watch?v=oXrn-n6YMks

### What is the expected behavior?

Bank and bag windows should not close after every transaction, items in bag should be updated.

### What actually happened?

Bank and bag windows close on every transaction

### Suggested Solution/Workaround

Disabling auto toggle for bank in Bags -> General -> Auto Toggle window seems to be a workaround. Disabling ElvUI completely and using default Blizzard UI works fine as well.

### Errors

```shell
No errors / LUA messages shown or captured in Bugsack
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by TheOrionsun** [comment] 2022-11-27 16:29
Hello,
I can confirm this issue, but it only happens on some of my toons while others don't have it.
I have tried to make it happen on the toons that don't, but the issue is only on some of my toons.
All my toons have the same ELVUI profile, and same wow profile settings.

In past versions of Elvui and Pawn when I disabled Pawn the problem would go away. This however does not work with the new Pawn pdate 2.7.12. Not sure what the relationship could have been.

Trying a reinstall of wow to see what happens. That should reset all my toon's wow settings. I will then copy over my Elvui files so I can get my profiles back.…

Done with the reinstall and the problem is persistent, so this can only be that there are different settings in each toon’s Elvui even when they use the same profile.

There may also be something that each toon has that the other does not, like a type of bag in their bank slots or an item….or just a quest or almost anything that differs from toon to toon....

**Comment by madmann26** [comment] 2022-11-30 13:30
This is also happening to me. Toggling the bags off/on and /reloadui seems to fix it for the current session but reverts when I log out/in.

**Comment by 1Botanica1** [comment] 2023-04-30 08:36
Is this still an issue?

If so, please delete ElvUI, ElvUI_Options & ElvUI_Libraries from your addons folder & download again & test.

**Comment by kodewdle** [comment] 2023-05-01 22:21
this is old, closing it. reopen if needed. :)

**Closed by kodewdle** 2023-05-01 22:21 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
