### ISSUE TITLE
[Retail Bug Report] <extra action button remains>

### ISSUE THREAD

**Issue by vixiepixie5** [tukui-org/ElvUI#881] opened 2023-02-28 22:48 UTC
### What is the issue you are having?

I'm still seeing the extra action button, despite using ElvUI bars. I've tried the add-on shuffle, restarting my WTF, and to the best of my abilities checked settings of my arsons for an issue. 

### What is the expected behavior?

Extra Action Button is replaced with ElvUI buttons.

### What actually happened?

Both ElvUI and the Blizzard button shows and tje blizzard one cant be moved. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment] 2023-03-01 11:44
Type in chat in game 
/edebug on

test.  Do you still have the issue?  

If so, type in chat 
/estatus 

and upload a full UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by vixiepixie5** [comment] 2023-03-02 13:46
Im on campus until around 17,00 EST. I'll fire up the PC and test everything and post a screen shot. No cropping with highlighting the area of issue. Should be done tonight or tomorrow. 

Thanks for all the hard work!

**Comment by vixiepixie5** [comment] 2023-03-02 14:32
Went and had a friend take a crack at it. They're a software engineer something about lua. They said it's solved, apparently I didn't reload the addons after deleting the WTF or something. Basically, seems solved by their word. 

I'll keep it open, and still report back. But, I'd worry about other bugs for now if you want. Be well.

**Comment by 1Botanica1** [comment] 2023-03-02 19:02
If the issue is solved, then close the ticket.  

If you have issues, reopen with the requested information.

**Comment by kodewdle** [comment] 2023-03-02 19:08
closing for now, reopen if needed

**Closed by kodewdle** 2023-03-02 19:08 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
