### ISSUE TITLE
Healer Mana only display

### ISSUE THREAD

**Issue by kirin6666** [tukui-org/ElvUI#1002] opened 2023-06-29 13:02 UTC
**Is your feature request related to a problem? Please describe.**
Right now there's only two ways to display resources on party and raid unit frames - all resources and no resources. 

**Describe the solution you'd like**
I'd like to have the option to display only healer's mana as a third option. I like to have the least amount of clutter on my screen, but I do find myself often needing to know about my healer's mana situation, whether in raid or in party group. If you're not showing any - you're unaware, but if you're showing all - then you're seeing all kinds of stupid crap like runic power or astral power. I find that irrelevant when I only want the mana.

**Describe alternatives you've considered**
Alternatives include installing a weakaura (not a fan of having 25 thousand weakauras, especially when an addon can be way better if optimized compared to a WA). Another alternative is Vuhdo but then u have to know/install/learn an additional addon just for that sake.

**Additional context**
Hope it was clear enough and argumentative enough.

**Comment by 1Botanica1** [comment] 2023-06-30 07:37
Duplicate of #923

**Comment by a-kharkov** [comment] 2023-11-02 12:04
I wonder how it is a duplicate of a completed issued when it's not implemented

**Comment by Azilroka** [comment] 2023-11-02 13:17
Just because it's not implemented doesn't mean that it's not a duplicate of the request for healer mana.

**Comment by Repooc** [comment] 2023-11-17 07:39
Made a elvui plugin for this as we don't have plans to implement this into elvui at this time.
Alpha version on [wago](https://addons.wago.io/addons/elvui-healeronlypower/versions?stability=alpha).

**Closed by Repooc** 2023-11-17 07:39 UTC
Labels: 💡Pending 🕐
