### ISSUE TITLE
[Retail Bug Report] ElvUI Nameplate appears with Blizzard Nameplates

### ISSUE THREAD

**Issue by Joris-ROBIN** [tukui-org/ElvUI#920] opened 2023-03-26 09:55 UTC
### What is the issue you are having?

The default nameplates of world of warcraft are displayed in addition to that of elvui nameplates

### What is the expected behavior?

I prefer elvui nameplate so i want to un-shiw wow nameplate

### What actually happened?

After i download the 13.29 and put it in the addons folder of world of warcraft, this issue appear. 

I have try some options in elvui or wow options but noting works. 
I have disabled all addons except elvui, the issue still in game. 
I have no lua error

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment] 2023-03-27 21:48
@Joris-ROBIN 
Do you update ElvUI manually or via a client (tukui client etc) 

If you update manually, do you delete all three folders first 
ElvUI
ElvUI_OptionsUI 
&
ElvUI_Libraries 

and then place the new folders in, or do your copy over those folder or not update all 3?

**Comment by kodewdle** [comment] 2023-04-24 23:27
confirmed this is fixed in dev branch and main when updating the folders properly, read what @1Botanica1 said :) thanks! 🌼

**Closed by kodewdle** 2023-04-24 23:27 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail

**Comment by cr00k3r** [comment] 2023-07-20 02:09
Hi team. I'm experiencing this same issue now. I am also using Eltruism and mMediaTag & Tools along with ElvUI. I update using WoWUP. Any ideas?

**Comment by 1Botanica1** [comment] 2023-07-20 02:12
> Hi team. I'm experiencing this same issue now. I am also using Eltruism and mMediaTag & Tools along with ElvUI. I update using WoWUP. Any ideas?


Check top of the ElvUI menu in game, should be 13.38.  If not, update.  
Type in chat in game 
`/edebug on`

If you still have the issue, type in chat in game 
`/estatus` 
And upload a full ui screenshot (no cropping) showing both the issue and the status panel.

**Comment by cr00k3r** [comment] 2023-07-20 02:22
![image](https://github.com/tukui-org/ElvUI/assets/1480663/3a7f7793-f194-476a-a741-f1140c037662)
![image](https://github.com/tukui-org/ElvUI/assets/1480663/e0a8fb4c-0930-4a07-9ec8-af09c8fe0715)

Thanks for the quick reply. When enabling edebug the issue does not occur, so I took a screenshot as requested with estatus on. I also took another screenshot whilst edebug was off so that you can see the issue during normal gameplay.

**Comment by cr00k3r** [comment] 2023-07-20 02:25
![image](https://github.com/tukui-org/ElvUI/assets/1480663/72c2d4ac-9e9f-4a14-8a96-f6759af70d7d)
Added another screenshot with the Eltrium and mMediaTag & Tools addons disabled.

**Comment by 1Botanica1** [comment] 2023-07-20 02:27
If the issue doesn't happen with only ElvUI, then it isn't an ElvUI problem - it is caused by another addon. 

You may have another nameplate addon enabled, if so, disable it.   You can't have two addons trying to control the same element.  

But you will need to find the other causing the issue and either disable or report to the author of that addon.

**Comment by 1Botanica1** [comment] 2023-07-20 02:41
> ![image](https://github.com/tukui-org/ElvUI/assets/1480663/72c2d4ac-9e9f-4a14-8a96-f6759af70d7d)
> 
> Added another screenshot with the Eltrium and mMediaTag & Tools addons disabled. 

There is no need to do anymore screenshot or troubleshooting. 

This is for issues with ElvUI. You have established that it isn't an issue with ElvUI 

Please see my other comment.

**Comment by cr00k3r** [comment] 2023-07-20 02:46
> > ![image](https://user-images.githubusercontent.com/1480663/254754484-72c2d4ac-9e9f-4a14-8a96-f6759af70d7d.png)
> > Added another screenshot with the Eltrium and mMediaTag & Tools addons disabled.
> 
> There is no need to do anymore screenshot or troubleshooting.
> 
> This is for issues with ElvUI. You have established that it isn't an issue with ElvUI
> 
> Please see my other comment.

Ok. Thanks for your help.
