### ISSUE TITLE
ptr 행동단축바가 안됩니다

### ISSUE THREAD

**Issue by tararkorb** [tukui-org/ElvUI#1364] opened 2024-09-13 16:02 UTC
### Troubleshooting Steps

![5555](https://github.com/user-attachments/assets/5f08adcf-1f0c-4747-8159-f6642b09d9ce)

### Describe the expected behavior and what actually happened?

저 밑에 스킬바가 보여야하는데 안보입니다 지금 저 lua 오류는 행동단축바에 단축키설정을 눌렀더니 저렇게 나옵니다

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:454: attempt to index local 'frame' (a nil value)
Time: Sat Sep 14 01:00:40 2024
Count: 2
Stack: Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:454: attempt to index local 'frame' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3-ElvUI/AceGUIWidget-Button-ElvUI.lua"]:85: in function <...raries/Core/Ace3-ElvUI/AceGUIWidget-Button-ElvUI.lua:82>
[string "=[C]"]: ?

Locals: frame = ElvUIAceGUI30Button1 {
 Right = Texture {
 }
 Middle = Texture {
 }
 template = "Default"
 obj = <table> {
 }
 height = 24
 glossTex = true
 PixelSnapDisabled = true
 TopRightCorner = Texture {
 }
 RightEdge = Texture {
 }
 isEdited = true
 IsSkinned = true
 Center = Texture {
 }
 BottomEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 Text = ElvUIAceGUI30Button1Text {
 }
 BottomLeftCorner = Texture {
 }
 width = 160
 Left = Texture {
 }
 fitTextWidthPadding = 40
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 LeftEdge = Texture {
 }
 fitTextCanWidthDecrease = true
}
AceGUI = <table> {
 objPools = <table> {
 }
 WidgetBase = <table> {
 }
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 tooltip = AceGUITooltip {
 }
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 WidgetContainerBase = <table> {
 }
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2024-09-13 20:13
Duplicate of #1356 

There is no support for the ptr.

Please do not report errors.

**Closed** 2024-09-13 23:27 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Wrath ❄️
