### ISSUE TITLE
LUA error with fly out action on portals/teleports

### ISSUE THREAD

**Issue by engineeringmage** [tukui-org/ElvUI#602] opened 2022-11-19 12:15 UTC
### What is the issue you are having?

Fly out for portals/teleports results in LUA error
<img width="1440" alt="2022-11-19_06-14-08" src="https://user-images.githubusercontent.com/98777401/202850349-4252f02c-8de5-4979-84c1-aebf31808821.png">

### What is the expected behavior?

Upon clicking teleport or portal fly out action, icons for each available location should be present

### What actually happened?

LUA error

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sat Nov 19 06:09:35 2022
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Arcanemagus** [comment] 2022-11-20 22:23
Duplicate of #589.

**Closed** 2022-11-21 01:50 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
