### ISSUE TITLE
[Retail Bug Report] Unable to right-click usable items in bags.

### ISSUE THREAD

**Issue by MatuMikey** [tukui-org/ElvUI#520] opened 2022-11-05 17:40 UTC
### What is the issue you are having?

After loading up an ElvUI profile, doesn't matter which one or how it was loaded, I am unable to use most "usable" items in my bags like a hearthstone. I am able to right click on container type items but everything else just doesn't get clicked on. I disabled all add-ons except ElvUI and the issue persists. I disabled ElVUI and re-enabled all other add-ons and I was able to right click again.

### What is the expected behavior?

If I right click on a usable *non-container* type i.e. like a hearthstone item in my bags it should initiate the /use <item> command.

### What actually happened?

The item gets clicked but is not used and an in-game sound plays that sounds like those lockboxes that need a key when you try open it without a key.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Eldranil** [comment] 2022-11-05 19:11
I have been having the same issue but I managed to reproduce it when ElvUI's bag module is disabled. I think I also reproduced it when ElvUI was entirely off but it's been a while and can't be certain anymore on that last one. It might be worth having people confirm whether this is an ElvUI issue.

This is a problem that comes and goes, which makes it annoying to track. I suspect `\reloadui` can potentially make it go away. For now, a workaround is to put the item to an action bar (even an ElvUI action bar works) and use it from there.

**Comment by juouyang** [comment] 2022-11-06 12:32
Same here, `/reload ui` used to work for a short peroid before items become un-usable in bags again.
But for 12.99, the `/reload ui` does not works anymore

**Comment by Frippez73** [comment] 2022-11-07 13:47
I have the same problem as I reported in ticket [#514](https://github.com/tukui-org/ElvUI/issues/514). My ticket was closed complete without any comments almost immediately even though the issue is still there.

**Comment by Toasticon** [comment] 2022-11-08 17:54
Only `/reload` is required for a few years now.

**Comment by Azilroka** [comment] 2022-11-08 20:25
@Toasticon so you been reloading the dragonflight taint for bags for almost 2 years?
@Frippez73 it has been fixed in development.. Which was supposed to be released shortly after I closed the ticket.

What the issue is.. with the skin the taint was fixed.. We didn't test it without the skin.

**Comment by Remuelso14** [comment] 2022-11-08 21:14
I have the same bug. Just checked - it appeared after opening any bags with resourses in backpack. For example: "Shipment of Elethium Ore" from Ko'tul in Oribos.
But sometimes it works good and I can open more than one bags with stuff at once...
And I can solve it temporary by using /rl command.

**Comment by Toasticon** [comment] 2022-11-08 21:57
> @Toasticon so you been reloading the dragonflight taint for bags for almost 2 years? @Frippez73 it has been fixed in development.. Which was supposed to be released shortly after I closed the ticket.
> 
> What the issue is.. with the skin the taint was fixed.. We didn't test it without the skin.

I don't use elvui bags because the sorting method is utter garbage not to mention the lack of proper "bagbrother" functionality.

**Comment by jwld** [comment] 2022-11-09 08:03
Yep I'm seeing this too - it's a big pain since I can't disenchant things in the bags either. I'm not using ElvUI's bags.

**Comment by Brdrker** [comment] 2022-11-10 00:47
Date: 2022-11-09 19:46:42
ID: 4
Error occured in: AddOn: ElvUI
Count: 1
Message: Error: AddOn ElvUI attempted to call a forbidden function (UseContainerItem()) from a tainted execution path.
Debug:
   [string "=[C]"]: UseContainerItem()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1384: ContainerFrameItemButton_OnClick()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1435:
      Interface/FrameXML/ContainerFrame.lua:1423
Locals:
None
AddOns:
  Swatter, v<%version%> (<%codename%>)
  APRCore, v13
  AskMrRobot, v114
  Auctioneer, v9.1.BETA.5.4 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.4 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.4 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.4 (OneMawTime)
  BadBoy, vv10.0.0
  BtWQuests, v2.23.0
  BtWQuestsShadowlands, v6.5
  CanIMogIt, v10.0.0v1.36
  CovenantMissionHelper, v3.2.0
  DBMCore, v5b00279
  DBMStatusBarTimers, v5b00279
  DBMVPVEM, v0dab85c
  ElvUI, v12.99
  GatherMate2, v1.48.0
  HandyNotes, vv1.6.12
  HandyNotesBattleForAzerothTreasures, vv28.2
  HandyNotesLegionTreasures, vv30.2
  HandyNotesShadowlands, v48
  HandyNotesShadowlandsTreasures, vv71.3
  HandyNotesTreasureHunter, vv29.2
  Hekili, vv10.0.0-08.5
  idTip, v10.1.1
  ItemRack, v
  LiteMount, v10.0.6
  LoggerHead, v10.0.0
  MacroToolkit, vv10.0.0-6
  MacroToolkitIcons, v7.2.0.0
  MBB, v4.0.16
  Omen, v3.2.4
  oRA3, vv10.0.2
  Pawn, v2.7.7
  PetTracker, v10.0
  Postal, vv3.8.7
  RareScanner, v10.0.0.4
  Recap, v5.30
  Scrap, v10.0.3
  Simulationcraft, v10.0.0-3
  SmartBuff, v11.10000
  Stubby, v9.1.BETA.5.4 (OneMawTime)
  TomCats, v2.4.23
  TomTom, vv3.3.4-release
  WorldQuestsList, v105
  BlizRuntimeLib_enUS v10.0.0.100000 <none>
  (ck=4d4)

**Comment by FoxVenture** [comment] 2022-11-11 17:51
I'm having the same problem since the new blizz UI. I'm not using the Elvui bags and I have the skins disables. It happens after taking a portal or using a hearthstone. /reload seems to temp fix it until you use a portal again or moving the item to an actionbar and clicking it with the mouse.

A friend was using Elvui but with the blizz actionbars (so everyhthing in Elvui actionbars disabled) and all skins also disabled. And had almost the same problem. But for the actionbar the keybinds didnt work and clicking it with the mouse did work.

**Comment by Frippez73** [comment] 2022-11-12 06:21
> @Frippez73 it has been fixed in development.. Which was supposed to be released shortly after I closed the ticket.
> > What the issue is.. with the skin the taint was fixed.. We didn't test it without the skin.

@Azilroka  Thanks for the info! I updated to 13.00, tested and it worked fine to right click items when I logged in.
However, when I ported in to a dungeon it stopped working again. I had to do a /reloadui and then it worked again when inside the dungeon. So something is still funky.
Thanks for investigating!

**Comment by CrimsonChaord** [comment] 2022-11-13 11:26
Pretty sure this is specifically happening when elv actionbars are disabled. Bumping for giga priority

**Comment by bigbooksfan** [comment] 2022-11-13 19:04
I can confirm that problem is fixed now! Just update mod

**Comment by Frippez73** [comment] 2022-11-14 07:00
> > @Frippez73 it has been fixed in development.. Which was supposed to be released shortly after I closed the ticket.
> > > What the issue is.. with the skin the taint was fixed.. We didn't test it without the skin.
> 
> @Azilroka Thanks for the info! I updated to version 13.00, tested and it worked fine to right click items in bags when I logged in. However, when I ported in to a dungeon it stopped working again. I had to do a /reloadui and then it worked again when inside the dungeon. So something is still funky. Thanks for investigating!

Update as of 2022-11-14 I can confirm that I still have the issue with version 13.01.
Works fine when I log in but as soon as I port somewhere, a dungeon for example it happens again. Then I can't right click any bag items and need to do a /reloadui.

**Comment by Frippez73** [comment] 2022-11-17 09:53
> Update as of 2022-11-14 I can confirm that I still have the issue with version 13.01.
> Works fine when I log in but as soon as I port somewhere, a dungeon for example it happens again. Then I can't right click any bag items and need to do a /reloadui.

@Azilroka Update as of 2022-11-17 I can confirm that I still have the issue with version 13.02.
Works fine when I log in.
As soon as I port somewhere, a dungeon for example then I can't right click any bag items and need to do a /reloadui.

**Comment by Frippez73** [comment] 2022-11-18 11:49
> > Update as of 2022-11-14 I can confirm that I still have the issue with version 13.01.
> > Works fine when I log in but as soon as I port somewhere, a dungeon for example it happens again. Then I can't right click any bag items and need to do a /reloadui.
> 
> @Azilroka Update as of 2022-11-17 I can confirm that I still have the issue with version 13.02. Works fine when I log in. As soon as I port somewhere, a dungeon for example then I can't right click any bag items and need to do a /reloadui.

@Azilroka Update as of 2022-11-18 I can confirm that I still have the issue with version 13.03.

**Comment by jury** [comment] 2022-11-18 22:23
I'm also seeing this still on 13.04. 

I have ElvUI bags turned off, so even when right-clicking on the blizzard bag UI I'm getting this error

12x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

**Comment by Frippez73** [comment] 2022-11-20 08:16
> > > Update as of 2022-11-14 I can confirm that I still have the issue with version 13.01.
> > > Works fine when I log in but as soon as I port somewhere, a dungeon for example it happens again. Then I can't right click any bag items and need to do a /reloadui.
> > 
> > 
> > @Azilroka Update as of 2022-11-17 I can confirm that I still have the issue with version 13.02. Works fine when I log in. As soon as I port somewhere, a dungeon for example then I can't right click any bag items and need to do a /reloadui.
> 
> @Azilroka Update as of 2022-11-18 I can confirm that I still have the issue with version 13.03.

@Azilroka Update 2022-11-20 I can confirm that I still have the issue with version 13.04.

**Comment by bcn-calto** [comment] 2022-11-21 13:51
i have same issue 😢 
pls fix this problem for my peaceful wow play

**Comment by Frippez73** [comment] 2022-11-23 06:40
> > > > Update as of 2022-11-14 I can confirm that I still have the issue with version 13.01.
> > > > Works fine when I log in but as soon as I port somewhere, a dungeon for example it happens again. Then I can't right click any bag items and need to do a /reloadui.
> > > 
> > > 
> > > @Azilroka Update as of 2022-11-17 I can confirm that I still have the issue with version 13.02. Works fine when I log in. As soon as I port somewhere, a dungeon for example then I can't right click any bag items and need to do a /reloadui.
> > 
> > 
> > @Azilroka Update as of 2022-11-18 I can confirm that I still have the issue with version 13.03.
> 
> @Azilroka Update 2022-11-20 I can confirm that I still have the issue with version 13.04.

@Azilroka Update 2022-11-23 Problem persists in version 13.06.

**Comment by Syrchalis** [comment] 2022-11-24 13:17
`22x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>`

Please fix this, it is INSANELY annoying having to reload basically any time you want to use a quest item, consumable, anything from your bag or having to drag everything on your bar.

**Closed** 2023-02-17 01:34 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
