### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by AtlantiQ** [tukui-org/ElvUI#998] opened 2023-06-19 06:53 UTC
### What is the issue you are having?

Fps started to drop a lot in M+ and raid

### What is the expected behavior?

Usually this problem was not, but the last few days to play it became unbearable

### What actually happened?

 3x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:587: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:576>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2943: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2850: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2651: in function <FrameXML/UIParent.lua:2647>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3253: in function <FrameXML/UIParent.lua:3232>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2422: in function `EncounterJournal_OpenJournal'
[string "@Blizzard_SharedMapDataProviders/EncounterJournalDataProvider.lua"]:94: in function `OnMouseClickAction'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:156: in function `OnClick'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:154: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:151>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment] 2023-06-20 01:22
Duplicate of #989

**Comment by kodewdle** [comment] 2023-07-14 10:07
continue on https://github.com/tukui-org/ElvUI/issues/989

**Closed by kodewdle** 2023-07-14 10:07 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
