### ISSUE TITLE
after using blizzard edit mode interface functions stop operating (start menu, character sheet etc)

### ISSUE THREAD

**Issue by Dagowina** [tukui-org/ElvUI#1286] opened 2024-08-04 15:53 UTC
### Troubleshooting Steps

on /edebug on the issue doesn't seem to be reproduceable
![grafik](https://github.com/user-attachments/assets/2097c8f5-c7e9-4b8d-8ffe-dec47818d86f)

### Describe the expected behavior and what actually happened?

after switching the profile in the blizzard edit mode, bugsack announced a new lua error (posted below) and i could not access the start menu and character sheet anymore (maybe more, that's what i noticed)

### Reproducing the issue.

before using debug mode the issue was reproduceable after alt+f4 and restarting the game
after using the debug mode issue was not reproduceable after /rl, relog and restart

### Lua Errors

```shell
2x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'PetFrame:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UnitFrame/PetFrame.lua"]:169: in function `UpdateShownState'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:2244: in function `RefreshPetFrame'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:1726: in function `OnEditModeEnter'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:88: in function `EnterEditMode'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:113: in function <...ddOns/Blizzard_EditMode/Mainline/EditModeManager.lua:111>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:487: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:294: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:173: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:168>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:878: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:856>
[string "=(tail call)"]: ?
[string "@Blizzard_GameMenu/Standard/GameMenuFrame.lua"]:68: in function <Blizzard_GameMenu/Standard/GameMenuFrame.lua:65>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2024-08-04 20:20
Please follow all the troubleshooting steps when opening a ticket.

Type in chat in game
/edebug on
Test - change zones etc, does it break?
Do you still have the issue?
If you still have issues after edebug on, type in chat in game
/estatus and upload a FULL UI screenshot showing the issue and the status panel.

**Comment by 1Botanica1** [comment] 2024-08-04 20:21
If you don’t have the issue with edebug on (which disables all addons except ElvUI) then it doesn’t seem to be an ElvUI issue.  

You will have to find out which addon is causing the issue and report to the authors of that addon.  

This is for reporting error in ElvUI - not other plugins/addons.

**Comment by kodewdle** [comment] 2024-08-09 05:34
i can't reproduce this and so i will close this issue.  try without `ElvUI Enhanced Again` and see if you have the problem from that.  otherwise if you have steps to reproduce this with `/edebug on` please reopen and provide the steps so i can get the error on my end to resolve the problem, thank you!

**Closed by kodewdle** 2024-08-09 05:34 UTC
Labels: 🧬 Retail 🐲, 🐛 Possibly Unfixable ⚠️
