### ISSUE TITLE
Fonts.lua

### ISSUE THREAD

**Issue by fears** [tukui-org/ElvUI#1073] opened 2023-10-29 20:23 UTC
### What is the issue you are having?

The unified font no longer functions as it did from its inception after updating to version 13.46.

### What is the expected behavior?

The expected behavior is to follow the default font which I have set at 16 and I have never changed not suddenly decide to be 12 :P

### What actually happened?

Line 173 in fonts.lua was changed and no longer follows default font for professions tab and world map timers. It for whatever reason defaults to fontsize 12 despite having my default set to 16

Old behavior : E:SetFont(_G.SystemFont_Med1,                        NORMAL, size)
New behavior : E:SetFont(_G.SystemFont_Med1,                        NORMAL, stock and size or 12)

### Suggested Solution/Workaround

If I change the numerical value to 16 it works as it always has, but if I leave that 12 there it does not follow my default font and stays at fontsize 12

### Errors

```shell
None - thanks for your hard work Elv and crew :)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment] 2023-10-30 19:37
see how you feel about dev branch, [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)
working on making this more how i want them, it should work in your case better.
getting rid of unified fonts and adding a new setting that will use blizzard font size only if someone want that, otherwise it will scale the font by your Font Size setting (as it was intended in first place)

**Comment by fears** [comment] 2023-10-30 23:24
Its definitely the streamlined option I personally like. Unified fonts was always confusing because everything didn't inherit the fonts correctly across every option. Like I know 12 as a default font size is not something I'd ever use anywhere and my lowest and most comfortable is 16 so back in the day I'd just fork, edit tons of fonts/lua files and pull the UI and edit it for myself. Last few years I just got lazy and would just copy/paste the fonts.lua to my liking.  Thanks for your time man it's much appreciated :)

**Comment by kodewdle** [comment] 2023-10-31 11:57
we were talking about it on discord and i thought the same.  unified fonts wasn't really thought out well, it was messy and quite confusing.  feel free to reopen this if you test dev and notice a font that's a bit off.  i've been playing with the new changes myself on and off and keeping an eye out for any that seem to be a bit off.  closing issue for now. 👍

**Closed by kodewdle** 2023-10-31 11:57 UTC
Labels: 🧬 Retail 🐲

**Comment by fears** [comment] 2023-10-31 12:43
The ui makes the game enjoyable. Thanks for everything you do
