### ISSUE TITLE
[Retail Bug Report] The bottom-left/right options no longer work for individual target frame buff bars.

### ISSUE THREAD

**Issue by nequil17** [tukui-org/ElvUI#370] opened 2022-10-04 02:20 UTC
### What is the issue you are having?

After your recent update 9 days ago where I was spammed with needing to update, I noticed that the target frame's buff bars broke. I've attached screenshots.
![Screenshot 2022-10-03 211657](https://user-images.githubusercontent.com/29237377/193720422-5780cf99-94cc-4202-8da4-b010a883cbc6.png)
![Screenshot 2022-10-03 211741](https://user-images.githubusercontent.com/29237377/193720427-870f45f8-8f94-4198-a177-b58160835f0f.png)

### What is the expected behavior?

The buff frames should anchor to the very bottom of the bar, not inside of the frame.

### What actually happened?

I updated the addon to the latest version and it broke. I did a fresh install, turned off all addons, even gave it another attempt after i did a fresh windows install and its still broken.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment] 2022-10-04 21:24
It was bugged before.. It's been fixed.

**Comment by nequil17** [comment] 2022-10-05 02:24
Fixed in an upcoming patch or what? Your comment isn't helpful.

**Comment by Repooc** [comment] 2022-10-09 01:12
they were fixed in 12.89 if not mistaken and this is working as intended by the looks of it via my gifs that are attached
https://user-images.githubusercontent.com/1479745/194732920-ff913b53-56d3-4193-abf1-1e857278d594.mp4


https://user-images.githubusercontent.com/1479745/194732930-f55e5828-7b7b-429c-9362-36cd33742889.mp4

**Closed by Repooc** 2022-10-09 01:12 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail

**Comment by Repooc** [comment] 2022-10-09 01:14
https://user-images.githubusercontent.com/1479745/194732920-ff913b53-56d3-4193-abf1-1e857278d594.mp4

**Comment by nequil17** [comment] 2022-10-10 16:54
That doesnt make any sense, thats now how its supposed to work AT ALL. I've used elvui for years and it didn't break until i downloaded 12.91.
