### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [tukui-org/ElvUI#1138] opened 2023-12-18 19:46 UTC
### Troubleshooting Steps

all done

### Describe the expected behavior and what actually happened?

zone into Murozond's Rise dungeon and error pop up. 

### Reproducing the issue.

i zone in over and over again. 

### Lua Errors

```shell
35x ElvUI/Core/General/Math.lua:311: script ran too long
[string "@ElvUI/Core/General/Math.lua"]:311: in function <ElvUI/Core/General/Math.lua:311>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "collect"
(*temporary) = 0
(*temporary) = "script ran too long"
func = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
data = <table> {
 1 = "collect"
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2023-12-18 22:46
No, the troubleshooting steps are not "all done"  You haven't provided the information requested.  
See here https://github.com/tukui-org/ElvUI/wiki/troubleshoot

Also, a duplicate of your other issue, which you didn't do the troubleshooting steps in either.

**Closed** 2023-12-29 14:15 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Retail 🐲
