### ISSUE TITLE
[Retail Bug Report] 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'

### ISSUE THREAD

**Issue by zmoose** [tukui-org/ElvUI#846] opened 2023-02-08 19:32 UTC
### What is the issue you are having?

Updated to ElvUI 13.25 today.

Got the LUA error while doing the [Fishing Fenzy](https://www.wowhead.com/quest=72022/fishing-frenzy) world quest.

### What is the expected behavior?

No LUA error.

### What actually happened?

Message: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.

### Errors

```shell
Message: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
Time: Wed Feb  8 13:27:35 2023
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3161: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2632: in function <Interface/FrameXML/UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3179: in function <Interface/FrameXML/UIParent.lua:3177>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetPowerBarFrame.lua"]:8: in function `layoutFunc'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:530: in function `UpdateWidgetLayout'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:60: in function <...dOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua:57>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Timaeria** [comment] 2023-02-11 18:03
This error also appears during the WQ "Low Hanging Fruit" in Ohn'ahran Plains when attempting to shoot down the fruits using the extra action button.

**Comment by 1Botanica1** [comment] 2023-04-30 08:33
Duplicate of #735

**Comment by kodewdle** [comment] 2023-05-01 17:10
dup of https://github.com/tukui-org/ElvUI/issues/735 closing

**Closed by kodewdle** 2023-05-01 17:10 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
