### ISSUE TITLE
Cata PTR - 4.4.1 - Player Bars missing

### ISSUE THREAD

**Issue by NoCement** [tukui-org/ElvUI#1363] opened 2024-09-13 08:41 UTC
### Troubleshooting Steps

![obrazek](https://github.com/user-attachments/assets/c377c971-1a01-47f1-bb3a-4cb116ddcc56)

### Describe the expected behavior and what actually happened?

Player Bars should be visible. Even reset does not make them visible in Movers mode. I did download the version from PTR link.

### Reproducing the issue.

Logging into PTR, see bars are not there.

### Lua Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/DataBars/Reputation.lua:66: attempt to call upvalue 'C_Reputation_IsFactionParagon' (a nil value)
Time: Fri Sep 13 10:34:26 2024
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/DataBars/Reputation.lua:66: attempt to call upvalue 'C_Reputation_IsFactionParagon' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 85
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 UFParent = ElvUFParent {
 }
 wowtoc = 40401
 InfoColor2 = ""
 myname = "Thenameless"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.77-11-gcb06c3b"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Orc"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Orc"
 myclass = "WARLOCK"
 wowdate = "Sep 10 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Classic PTR Realm 1"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 Minimap = <table> {
 }
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = true
 Blizzard = <table> {
 }
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 PixelMode = true
 serverID = 4904
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-4904-00DC14F9"
 loadedtime = 134853.928000
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 texts = <table> {
 }
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ObjectEventFrame = Frame {
 }
 ConfigModeLocalizedStrings = <table> {
 }
 ModuleCopy = <table> {
 }
 SpecByClass = <table> {
 }
 resolution = "2560x1440"
 TutorialList = <table> {
 }
 ScanTooltip = Elv




Message: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1228: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
Time: Fri Sep 13 10:38:35 2024
Count: 1
Stack: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1228: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 85
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 UFParent = ElvUFParent {
 }
 wowtoc = 40401
 InfoColor2 = ""
 myname = "Thenameless"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.77-11-gcb06c3b"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Orc"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Orc"
 myclass = "WARLOCK"
 wowdate = "Sep 10 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Classic PTR Realm 1"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 Minimap = <table> {
 }
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = true
 Blizzard = <table> {
 }
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 PixelMode = true
 serverID = 4904
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-4904-00DC14F9"
 loadedtime = 135100.491000
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 texts = <table> {
 }
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ObjectEventFrame = Frame {
 }
 ConfigModeLocalizedStrings = <table> {
 }
 ModuleCopy = <table> {
 }
 SpecByClass = <table> {
 }
 resolution = "2560x1440"
 TutorialList



Message: ...ddOns/ElvUI/Core/Modules/Blizzard/TutorialFrames.lua:9: attempt to index field 'Advanced_UIScaleSlider' (a nil value)
Time: Fri Sep 13 10:38:35 2024
Count: 1
Stack: ...ddOns/ElvUI/Core/Modules/Blizzard/TutorialFrames.lua:9: attempt to index field 'Advanced_UIScaleSlider' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 85
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 UFParent = ElvUFParent {
 }
 wowtoc = 40401
 InfoColor2 = ""
 myname = "Thenameless"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.77-11-gcb06c3b"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Orc"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Orc"
 myclass = "WARLOCK"
 wowdate = "Sep 10 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Classic PTR Realm 1"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 Minimap = <table> {
 }
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = true
 Blizzard = <table> {
 }
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 PixelMode = true
 serverID = 4904
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-4904-00DC14F9"
 loadedtime = 135100.491000
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 texts = <table> {
 }
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ObjectEventFrame = Frame {
 }
 ConfigModeLocalizedStrings = <table> {
 }
 ModuleCopy = <table> {
 }
 SpecByClass = <table> {
 }
 resolution = "2560x1440"
 TutorialList = <table> {
 }
 ScanTooltip = ElvUI_ScanTooltip {


Message: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1135: doesn't exist!
Time: Fri Sep 13 10:38:36 2024
Count: 8
Stack: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1135: doesn't exist!
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 85
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 UFParent = ElvUFParent {
 }
 wowtoc = 40401
 InfoColor2 = ""
 myname = "Thenameless"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.77-11-gcb06c3b"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Orc"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Orc"
 myclass = "WARLOCK"
 wowdate = "Sep 10 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Classic PTR Realm 1"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 Minimap = <table> {
 }
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = true
 Blizzard = <table> {
 }
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 PixelMode = true
 serverID = 4904
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-4904-00DC14F9"
 loadedtime = 135100.491000
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 texts = <table> {
 }
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ObjectEventFrame = Frame {
 }
 ConfigModeLocalizedStrings = <table> {
 }
 ModuleCopy = <table> {
 }
 SpecByClass = <table> {
 }
 resolution = "2560x1440"
 TutorialList = <table> {
 }
 ScanTooltip = ElvUI_ScanTooltip {
 }
 locale = "enUS"
 CreditsList = <table> {
 }
 PluginInstaller = <table> {
 }
 myRaceID = 2
 Te
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment] 2024-09-13 12:12
Duplicate of #1356 

There is no support for the ptr.

Please do not report errors.

**Closed** 2024-09-13 12:14 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Classic 💀
