### ISSUE TITLE
[Retail Bug Report] Tooltips produce big empty dark window

### ISSUE THREAD

**Issue by Becca-J** [tukui-org/ElvUI#912] opened 2023-03-21 16:53 UTC
### What is the issue you are having?

Issue appeared after updating to 13.28 in the last hour.

When I mouse over abilities a dark box occurs on the screen. I'm not sure if this is happening when mousing over/clicking on other players/NPCs or items as well, I think it is sometimes but seems inconsistent.

I think it is trying to load a tooltip but there is no information in the dark box, and it's not in the expected place (see screenshots). Placement of dark box seems to vary a lot (including being in other places than in my example screenshots).

In one screenshot, big dark box covers much of right side of screen.
In other screenshot, dark box is smaller and located in bottom area over left part of main ability toolbars.

Issue goes away if I disable tooltips in ElvUI. Returns if I re-enable the module. I have not tried turning off individual options in the module. 

Occurs on 3 of 4 alts I've tested it on.

![WoWScrnShot_032123_163257](https://user-images.githubusercontent.com/13730550/226678296-4be11ca7-7b8d-4269-aa10-3b3d9d5eef54.jpg)
![WoWScrnShot_032123_163021](https://user-images.githubusercontent.com/13730550/226678270-255d177c-4104-4be9-a58d-cc6b7513c141.jpg)

I have tried disabling all other addons and issue persists.

Edit: I've realised that my chat panels also looks 'wrong' for these alts - the panels behind the chat/text box seem missing, but now I see there are additional empty black boxes* in the bottom right corner AND bottom left corner (underneath(?) part of my right chat panel). I think these are my chat panels but they are not the size and shape they should be. (*I.e. additional to the floating ones that occur when mousing over abilities/players/NPCs.) 

Further, the chat boxes themselves have been resized somehow. I have not changed any chat / chat panel settings today. If I disable tooltip module, the big dark boxes from mousing over abilities stop appearing, but it does not fix my chat panels or resize the chat box to how it should be. I don't know which options in the chat module might fix this.

I suspect some kind of tooltip bug that's also interacting somehow with panels. 
For reference, my chat panels (and tooltips) usually look something like this - screenshot taken a few days ago:

![WoWScrnShot_022523_214906](https://user-images.githubusercontent.com/13730550/226685331-2cd1bb92-bb04-44e3-b92e-70511a2bcc5c.jpg)

### What is the expected behavior?

- Not big black empty boxes on the screen when I mouseover abilities/players/NPCs.
- Tooltips with information in them. (Looking at third screenshot above, my tooltips are normally in the bottom right corner - currently there is an empty box in the current right corner.)
- Chat panels as they were (see third screenshot) not tiny little boxes in the corners of the screen; chat box size as it was. (I did not change any settings to make this happen, it's since the update.)

### What actually happened?

As described in "what is the issue you are having" and associated screenshots.

### Suggested Solution/Workaround

Sorry, no specific idea. I suspect today's update has caused the issue and I see from the changelog it included a lot of updates, so I guess it was something there.

Further thought - don't know if it helps but: I disabled all other addons except ElvUI to check if the problem persisted with just ElvUI loaded (it did). I then re-enabled my other usual addons, and at that point my bug tracker threw the error I have detailed in the box below - maybe there is useful info in it.

I do not think it is simply a clash with other addons as issues occur when just ElvUI is loaded.

### Errors

```shell
Date: 2023-03-21 16:46:00
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua line 78:
   attempt to index field 'TitleIconVersion' (a nil value)
Debug:
   [string "@Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua"]:78: in main chunk
Locals:
E = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:379
 mylevel = 62
 Bags = <table> {
 }
 Config_SetButtonColor = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:672
 Minimap = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 TBC = false
 OnPrivateProfileReset = <function> defined @Interface/AddOns/ElvUI/Core/init.lua:309
 ExitVehicleShowFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:433
 StaticPopup_EscapePressed = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:434
 Config_CreateLeftButtons = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:806
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1429
 GetMoverHolder = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:373
 CopyTable = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:600
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:450
 DisableMover = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:379
 FilterTableFromBlacklist = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:680
 ScheduleTimer = <function> defined @Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TagInfo = <table> {
 }
 PriestColors = <table> {
 }
 UpdateDB = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1398
 SetupTheme = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:191
 media = <table> {
 }
 UnlocalizedClassName = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:98
 TagFunctions = <table> {
 }
 OnPauseCooldown = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:237
 SetupChat = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:58
 GeneralMedia_ApplyToAll = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:336
 Flash = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:182
 StaticPopup_Hide = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1072
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 AddTag = <function> defined @Interface/AddOns/ElvUI/Core/General/Tags.lua:94
 FramesOverlap = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:164
 Config_CreateSeparatorLine = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:662
 GetZoneText = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:148
 SetEnabledState = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 Options = <table> {
 }
 GetPlayerMapPos = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:103
 toc = 100007
 Layout = <table> {
 }
 Config_DialogOpened = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:724
 MapInfo_CoordsUpdate = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:77
 MapInfo_CoordsStop = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:62
 PluginInstaller = <table> {
 }
 PixelBestSize = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:92
 UnregisterEventForObject = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1744
 Shake = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:154
 Distributor = <table> {
 }
 TimeColors = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1248
 HiddenFrame = Frame {
 }
 MapInfo_Update = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:22
 CreateStatusContent = <function> defined @Interface/AddOns/ElvUI/Core/General/StatusReport.lua:94
 Media = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 NewModule = <function> defined @Interface/AddOns/Masque/Libs/AceAd
AddOns:
  KalielsTracker, v6.1.1
  Swatter, v9.1.BETA.5.8 (OneMawTime)
  ACP, v3.5.7 
  AddonFactory, v10.0.011
  Altoholic, v10.0.011
  BetterWardrobe, v4.7
  DataStore, v2023.02.23
  DataStoreCharacters, v2023.02.23
  ElvUI, v13.28
  ElvUILibraries, v1.00
  Masque, v10.0.6
  TomTom, vv3.3.5-release
  BlizRuntimeLib_enUS v10.0.5.100005 <none>
  (ck=152)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment] 2023-03-28 07:54
this problem (the Tooltip one) is a side-effect of another addon (perhaps even a plugin to ElvUI).
it's hard to say which as you seem to have quite a few other things going alongside of ElvUI.

i would suggest trying to find the cause by first trying to replicate the issue with the tooltip then section out what mods you use, after you can get some steps to reproduce the issue.

as for the chat one, that *should be* good in 13.29 this was fixed cause some Wrath/Classic incompatibility happened.
for this one i would suggest manually deleting `ElvUI`, `ElvUI_Options`, and `ElvUI_Libraries` and reinstalling ElvUI but `backup your WTF folder first to be safe!` (or export your profile, whatever you chose~ just good to have a backup!) just to be sure something didn't go wrong with the update.

i will close this issue as, it's not produced during `/edebug on` - with a lot of other addons things like this are possible to happen easily, even if it really seems to be ElvUI as the cause.

if you need more help with this feel free to ask in the Discord if you haven't yet.🌼

**Closed by kodewdle** 2023-03-28 07:54 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
