### ISSUE TITLE
[Retail Bug Report] Exporting and importing a profile does not export the datatexts correctly

### ISSUE THREAD

**Issue by RaulRG** [tukui-org/ElvUI#155] opened 2022-01-28 18:05 UTC
### What is the issue you are having?

I exported a ElvUI profile from a computer with ElvUI 12.62 and imported the xml file in another one with ElvUI 12.62 as weill. 
Under "DataTexts" I had a panel called "MyPanel"  with 6 different datatexts. After importing the profile the panel "MyPanel" was there but somewhere else (the position is not restored) and I had 6 datatexts, but they were empty. 
The 6 datatexts were standard ones from ElvUI like "ElvUI Config", "System", ... and not something from another addon.

### What is the expected behavior?

Importing a profile should import the position of the custom panels in a DataText and the configured DataTexts.

### What actually happened?

The position was random (somewhere in the center of my screen) and the 6 DataTexts in the panel were empty.

### Suggested Solution/Workaround

See the expected behavior

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment] 2022-01-28 21:37
Duplicate of #156. DataText Panels Slots and Positions are stored in Normal Profile and the panel itself is in Global Profile.

**Closed by Azilroka** 2022-01-28 21:37 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail

**Comment by Azilroka** [comment] 2022-01-28 21:38
Both of the issues you created could have been explained in Discord.
