### ISSUE TITLE
[Retail Bug Report] right clicking items from the bag does not use the item

### ISSUE THREAD

**Issue by dezzuzu** [tukui-org/ElvUI#971] opened 2023-05-09 06:08 UTC
### What is the issue you are having?

Enabled all regular addons, including ElvUI. Issue persists.
Disabled all addons except for ElvUI. Issue persists.
Disabled all addons including ElvUI. Issue not present. (So the problem appears to be with ElvUI.)
No LUA errors that I can tell.

Issue details:

ElvUI set to load, ElvUI Bags disabled from within ElvUI settings as shown:

![1231321](https://user-images.githubusercontent.com/53851484/237009033-56556d69-5a5d-40d8-a328-f3b6914a5dc7.png)

Upon load-in, bags/inventory cannot be opened. Neither of the two bound hotkeys work, nor does clicking on the bags in the bag bar.

Anything that reloads the UI within the game (changing addon settings or simply forcing with /reloadui) will allow bags to open normally until logging out. Logging in and/or changing characters requires the UI to be forcibly reloaded before bags can be opened again.

Issue only occurs when ElvUI Bags are disabled; Behavior is normal if ElvUI Bags are enabled.

### What is the expected behavior?

when i right click the item directly in the bag, the item should be used or consumed

### What actually happened?

nothing happens when i right click the item in my bag once the bug occurs

### Suggested Solution/Workaround

/rl and the items in the bags right click correctly until it randomly breaks again

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment] 2023-05-09 21:48
Duplicate of #624

**Comment by kodewdle** [comment] 2023-07-14 10:16
continue on https://github.com/tukui-org/ElvUI/issues/624

**Closed by kodewdle** 2023-07-14 10:16 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
