### ISSUE TITLE
Masque skin error with ElvUI

### ISSUE THREAD

**Issue by ZelionGG** [tukui-org/ElvUI#1081] opened 2023-11-10 09:29 UTC
### What is the issue you are having?

Since 10.2 patch, my Masque skins are acting weird with ElvUI (no issues with other addons like WeakAuras or other ActionBar replacement addons), aspect ratio is not being applied correctly and icons are looking flattened.

### What is the expected behavior?

Icons are supposed to be zoomed in/cropped a bit to match my Masque shape (I used the Debug button in ElvUI and enabled Masque and my Masque skin only to reproduce) :
![image](https://github.com/tukui-org/ElvUI/assets/51028342/39ea96be-a681-4cee-8f00-dfd66f00cd99)

### What actually happened?

But icons are being flattened :
![image](https://github.com/tukui-org/ElvUI/assets/51028342/c4e8e7df-0918-4d00-85a7-8a87280d2f68)

### Suggested Solution/Workaround

The temporary fix to that is going into Masque Settings > Skin Settings > ElvUI > Check and uncheck "Enable" in the Scale section, that will make the icons looking good again until the next UI reload.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by MchaseCov** [comment] 2023-11-10 21:37
Experiencing the same as of 13.7+. Rolled back to 13.6 to check and this wasn't occurring, but that may just be due to version incompatibility lua errors along the way.

Doesn't happen with Masque disabled. Testing with a rolled back Masque didn't change anything.

![image](https://github.com/tukui-org/ElvUI/assets/67227108/85d43acd-0797-427b-aa02-59fbe3ccb4e7)

**Comment by kodewdle** [comment] 2023-11-10 21:43
try this: [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)

**Comment by ZelionGG** [comment] 2023-11-10 21:57
> try this: [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)

Confirm this fixed my issue 
![image](https://github.com/tukui-org/ElvUI/assets/51028342/5725bb00-27cb-481c-be23-af38bbd7167b)

**Comment by MchaseCov** [comment] 2023-11-10 23:26
> try this: [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)

Works for me as well!

**Comment by kodewdle** [comment] 2023-11-12 04:14
closing this, as it's confirmed to be fixed! :)

**Closed by kodewdle** 2023-11-12 04:14 UTC
Labels: 🐛 Needs Investigation ❓, 🧬 Retail 🐲
