### ISSUE TITLE
[Retail Bug Report] Minimap Mail icon location incorrect after reloadui or logon

### ISSUE THREAD

**Issue by mbeck242** [tukui-org/ElvUI#832] opened 2023-02-03 17:14 UTC
### What is the issue you are having?

Maps / Minimaps / Minimap buttons / Mail / Position

I have moved the minimap (details in screenshots) from position A to position B.  When the UI is loaded (via entering world or subsequently reloading the UI) the mail icon appears relative to position A, as opposed to the new position B.

Notes:  Settings in ElvUI config remain correct.  Adjusting any of the settings related to the icon instantly pops the icon to being related to position B.

### What is the expected behavior?

The mail icon should appear relative to the minimap's current position.

### What actually happened?

The mail icon appears relative to the minimap's default position.

### Suggested Solution/Workaround

In the mail icon on load look for any hardcoded positional reference. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by mbeck242** [comment] 2023-02-03 17:15
![minimapMail1](https://user-images.githubusercontent.com/124386762/216665612-bc1b76c2-5d02-4d5b-9d9b-b67de276375e.jpg)
![minimapMail2](https://user-images.githubusercontent.com/124386762/216665620-5a1e9773-dcc2-4d64-aab5-6cea7253229a.jpg)

**Comment by Azilroka** [comment] 2023-02-03 18:43
It's been address and fixed in dev. This is a duplicate of
https://github.com/tukui-org/ElvUI/issues/825
https://github.com/tukui-org/ElvUI/issues/822
https://github.com/tukui-org/ElvUI/issues/817
https://github.com/tukui-org/ElvUI/issues/813
https://github.com/tukui-org/ElvUI/issues/801

**Closed by Azilroka** 2023-02-03 18:43 UTC
Labels: :bug::question: Bug (Needs Investigation), :video_game: Retail
